[package]
name = "dtool"
version = "0.1.0"
authors = ["GB <guoxbin@gmail.com>"]
description = "A collection of develop tools"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
hex = "0.4.0"
chrono = "0.4.10"
bs58 = { version = "0.3.0", features = ["check"] }
base64 = "0.11.0"
urlencoding = "1.0.0"
parity-codec = "3.2"
